In [1]:
import pandas as pd
from flask import jsonify 
import json

In [3]:
sheet_names = pd.ExcelFile("Time_travel/would-brits-rather-time-travel-to-the-past-or-to-the-future.xlsx").sheet_names

In [4]:
dataset = {}
for sheet in sheet_names:
    data = pd.read_excel("Time_travel/would-brits-rather-time-travel-to-the-past-or-to-the-future.xlsx", sheet)
    dataset[sheet] = data

In [6]:
print(sheet_names)

['All adults', 'London', 'Rest of South', 'Midlands', 'North', 'Scotland', 'Wales', 'Male', 'Female', '18-24', '25-49', '50-64', '65+', 'ABC1', 'C2DE']

In [5]:
dataset["18-24"].head()

,"If you could travel in time and live in another era, would you rather go to the past or to the future?",2019-09-10,2020-09-07,2021-09-06,2022-09-04,2023-09-06,2024-09-04
0,The past,0.50,0.42,0.41,0.42,0.44,0.41
1,The future,0.36,0.40,0.44,0.37,0.42,0.43
2,Don't know,0.14,0.18,0.15,0.22,0.14,0.15
3,Unweighted base,161.00,178.00,150.00,142.00,163.00,236.00
4,Base,218.00,223.00,224.00,223.00,222.00,224.00

In [36]:
relevant = ['All adults','18-24', '25-49', '50-64', '65+']
df = pd.DataFrame(columns=["Group", "Future", "Past"])

In [42]:
full_df= df = pd.DataFrame(columns=["Group",  "Past","Future"])
for group in relevant:
    line = [[group, dataset[group]['2024-09-04'].iloc[0]*100, dataset[group]['2024-09-04'].iloc[1]*100]]
    df = pd.DataFrame(line, columns=["Group",  "Past","Future"])
    full_df = pd.concat([full_df, df], ignore_index=True)

In [43]:
full_df.index.name= 'index'
full_df.to_csv("Time_travel/Age_group_results.csv", index=True)

In [44]:
full_df

            Group  Past  Future
index
0      All adults  58.0    28.0
1           18-24  41.0    43.0
2           25-49  55.0    33.0
3           50-64  62.0    21.0
4             65+  66.0    17.0

In [27]:
df = pd.read_excel("which_government_would_make_jobs/which-government-would-be-better-at-providing-more-jobs.xlsx")
df = df.iloc[:-2]

In [28]:
df["Party"] = df["Which government do you think would be better for...Providing more jobs?"].apply(lambda x: "Labour" if "Labour" in x else "Conservative" if "Conservative" in x else "Unsure" if "Don't know" in x else x)

In [29]:
grouped_by_party = df.groupby("Party").sum()

/var/folders/qp/65q347gs0g1bnwxt8wqj3xsw0000gn/T/ipykernel_38454/1647301067.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  grouped_by_party = df.groupby("Party").sum()

In [30]:
grouped_by_party

,2019-07-10,2019-08-06,2019-09-02,2019-10-01,2019-10-28,2019-11-26,2019-12-30,2020-01-27,2020-02-24,2020-03-23,...,2024-01-07,2024-02-05,2024-03-04,2024-04-01,2024-04-28,2024-05-27,2024-06-24,2024-07-22,2024-09-02,2024-09-30
Party,,,,,,,,,,,,,,,,,,,,,
Conservative,0.26,0.31,0.32,0.30,0.32,0.31,0.36,0.38,0.36,0.40,...,0.17,0.16,0.16,0.14,0.15,0.17,0.14,0.11,0.16,0.19
Labour,0.21,0.18,0.18,0.22,0.22,0.28,0.22,0.21,0.20,0.21,...,0.29,0.32,0.30,0.30,0.32,0.32,0.34,0.38,0.29,0.29
Neither,0.32,0.28,0.25,0.25,0.26,0.21,0.20,0.19,0.23,0.16,...,0.31,0.30,0.34,0.32,0.31,0.31,0.31,0.26,0.33,0.34
Unsure,0.22,0.23,0.24,0.23,0.19,0.20,0.21,0.22,0.21,0.23,...,0.23,0.22,0.20,0.23,0.22,0.20,0.21,0.25,0.22,0.19

In [31]:
grouped_by_party.to_csv("which_government_would_make_jobs/All_adults_grouped_by_party.csv")